version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: blps-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: studs
      POSTGRES_USER: s413022
      POSTGRES_PASSWORD: 1i3O5V9ts2y1GN7M
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U s413022 -d studs"]
      interval: 5s
      timeout: 3s
      retries: 20

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: blps-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"
    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_jms_topic_exchange rabbitmq_management &&
             rabbitmq-server"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 20

volumes:
  postgres_data:
