spring.application.name=BLPS

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/studs}
spring.datasource.username=${DB_USER:s413022}
spring.datasource.password=${DB_PASSWORD:1i3O5V9ts2y1GN7M}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:create}
spring.jpa.properties.hibernate.format_sql=true

server.port=${SERVER_PORT:8080}

jwt.secret=${JWT_SECRET:01234567890123456789012345678901}
jwt.expiration=PT15M
jwt.issuer=blps

security.users.xml-path=classpath:security/users.xml

rabbitmq.host=${RABBITMQ_HOST:localhost}
rabbitmq.port=${RABBITMQ_PORT:5672}
rabbitmq.username=${RABBITMQ_USER:guest}
rabbitmq.password=${RABBITMQ_PASSWORD:guest}
rabbitmq.vhost=${RABBITMQ_VHOST:/}

app.jms.tariff-change-queue=${TARIFF_CHANGE_QUEUE:tariff.change.requests}
app.jms.feature-disable-queue=${FEATURE_DISABLE_QUEUE:feature.disable.requests}
app.jms.monthly-fee-queue=${MONTHLY_FEE_QUEUE:monthly.fee.requests}
app.scheduler.monthly-fee-cron=${MONTHLY_FEE_CRON:*/30 * * * * *}
app.scheduler.monthly-fee-cycle-pattern=${MONTHLY_FEE_CYCLE_PATTERN:yyyy-MM-dd-HH:mm}

app.scheduler.retry-cron=${RETRY_CRON:0 */1 * * * *}
